### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ExitPath** [annahung31/EMOPIA#2]
Hello, excuse me, I am very interested in this job, but I have two problems when running the code.   1. Can you provide the dataset that used in this work? or 2. Can you provide the code for data preprocessing?  Thank you！

**Comment by annahung31** [comment]
Hi,

You can take a look at the dataset preparation [here](https://github.com/annahung31/EMOPIA/tree/main/dataset), and the dataset is available on [Zenodo](https://zenodo.org/record/5151045#.YQaNfVMzZoQ).

Thanks,
Anna
