### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by ExitPath** [annahung31/EMOPIA#5]
Hello, excuse me, I am very interested in this job, but I find two bugs when running the code. 
1. There is no initialization parameter args.in_attn in workspace/transformer/main_cp.py;
2. The function self.transformer_encoder(pos_emb, attn_mask, emb_emotion=emo_embd)) in workspace/transformer/models.py has no emb_emotion parameter.

**Comment by annahung31** [comment]
Hi,

Thanks for point that out.

The in_attn parameter is used for an experiment that changes the architecture in the encoder. However, the attempt doesn't succeed, so we don't use it for the paper. I've deleted the parameter and also the different way to call self.transformer_encoder. Please pull the new version, thanks!

**Comment by ExitPath** [comment]
Thanks for your reply, but The function self.transformer_encoder(pos_emb, attn_mask ) in workspace/transformer/models.py still has a bug, this is 

"h, layer_outputs = self.transformer_encoder(pos_emb, attn_mask)  # y: b x s x d_model
ValueError: too many values to unpack (expected 2)", 

which means that self.transformer_encoder()  has only one output instead of two.

 and What is the version of your fast_transformers?

**Comment by annahung31** [comment]
The additional output also comes from my modified fast-transformer, so I already deleted it, please pull the newest version again. Thanks for letting me know and apologized for the inconvenience!
