### ISSUE TITLE
Where to find the timestamp for each segmented audio clip?

### ISSUE THREAD

**Issue by deepspike** [annahung31/EMOPIA#6]
According to the dataset description on the Zenodo, I suppose the timestamp for each audio clip should be included in the label.csv file. While within this file, only the clip index within a particular song can be found. Did you segment the whole song with equal length? If so what is the duration for each clip, otherwise, how can I determine the timestamp?

**Comment by annahung31** [comment]
Hi,

1. For the timestamp information, please get the latest version of EMOPIA: [EMOPIA 2.2](https://zenodo.org/record/5257995#.YTrJaZ4zZoQ). It contains a file called `timestamps.json` for easier usage. It records all the timestamps in dict format. The notebook `scripts/load_timestamp.ipynb` shows the format example.  Or you can also access `tagging_lists/` for timestamps of each file. Also, you can use `scripts/timestamp2clip.py` to get audio clips using timestamps.

2. We don't segment the whole song with equal length. We choose the segment with a specific emotion and try to cut the endpoint at the end of the music sentence. As a result, there might be 1 or more segments per song. 

3. A reminder: if you want to use the data for full-song analysis, you might need to notice that there are a few songs that are actually playlists on YouTube. So if a song contains many segments (for example 10+), it might be a playlist from YouTube.

**Comment by deepspike** [comment]
Thanks a lot for the quick update.
