### ISSUE TITLE
4Q and annotators

### ISSUE THREAD

**Issue by piaoziyue** [annahung31/EMOPIA#7]
Thank you so much for your great dataset. Here I am a little confused about the 4Q and annotators. I read your paper, and based on my understanding, 4Q are Q1 = HVHA, Q2 = HVLA, Q3 = LVHA, Q4 = LVLA, is that correct? And the 'label.csv' on zenodo, the annotator features are ABCD. What does that mean?

**Comment by piaoziyue** [comment]
And how do you define high and low? For example, arousal>0.6 is high?

**Comment by piaoziyue** [comment]
I understand! Sorry I didn't understand Q is quadrant. Thanks!

**Comment by annahung31** [comment]
1. 4Q are Q1 = HVHA, Q2 = HVLA, Q3 = LVLA, Q4 = HVLA. It's called Russel's 4Q emotion model. You might refer to our [demo page](https://annahung31.github.io/EMOPIA/)("Example of the dataset") for example, or this [image](https://www.researchgate.net/figure/The-2D-valence-arousal-emotion-space-Russell-1980-the-position-of-the-affective_fig1_254004106) for brief understanding.

2. The annotator in label.csv means the person who annotated that clip. There are 4 people who worked together to annotate the dataset, so the ABCD represents different people. We offer this information in case someone interested in the bias of annotation that comes from personal subjectivity.
