### ISSUE TITLE
How to generate REMI data by models?

### ISSUE THREAD

**Issue by yen52205** [annahung31/EMOPIA#9]
Hi,
In the paper, I notice that the model used for Emotion(4Q/Valence/Arousal) classification in Objective metrics is LSTM-Att + REMI.
But In the repo, the CP transformer model will generate a .mid file and a .npy for one music clip.
Could I use both of them to generate REMI data? And how to generate the REMI data type output?
1. The evaluation method:
![image](https://user-images.githubusercontent.com/48942210/147880044-6ee6dde7-ad61-42e9-98c7-791c508a26da.png)
2. The metrics:
![image](https://user-images.githubusercontent.com/48942210/147879955-e83c741d-b4fb-4665-b908-7a2d819af3d8.png)

thanks.

**Comment by joann8512** [comment]
REMI is the type of symbolic representation we used in the task. You can follow the steps [here](https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md) for data preprocessing.

**Comment by yen52205** [comment]
Firstly, thanks for answering this issue.

If it's possible, I want to check one more thing about transforming REMI.
Are .npy files generated by model "corpus" ?
So that I should use "From Corpus to Representation" part in preprocessing to transform REMI from .npy files?

Below is part of description from the link you mentioned.
ex.
  ![image](https://user-images.githubusercontent.com/48942210/151668038-6d52dbd1-088c-4485-873d-0c314122aedc.png)

**Comment by joann8512** [comment]
Just to be clear, the step of getting REMI representation is only during the steps of data preprocessing, so we haven't gone into the model yet. And yes, the codes for the step "Corpus to Representation" is explicitly for converting midi to the representation.

**Comment by yen52205** [comment]
Thanks for your answering
But I'm still confusing about the metrics in paper.

In the paper, you used LSTM-att+REMI to test the generation model's outputs.
But in your post-processing code, the generation model would output npy file and MIDI file.
Then how could I use LSTM-att +REMI to test the output of generation model (npy and MIDI files), when LSTM-att+REMI was supposed to eat REMI files?

if I want to reproduce the results in paper, should I use "Corpus to Representation" on the MIDI files that generated by generation model to get REMI representation, and feed those REMI files into LST-att+REMI to get classification accuracy?

Thanks.

**Comment by joann8512** [comment]
1. LSTM-att+REMI was used for the task of emotion classification
2. The generation model only outputs MIDI file, no npy file
3. Per your need, this [link](https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md) here shows you how to transform MIDI files to REMI representation

**Comment by yen52205** [comment]
> 1. LSTM-att+REMI was used for the task of emotion classification
> 2. The generation model only outputs MIDI file, no npy file
> 3. Per your need, this [link](https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md) here shows you how to transform MIDI files to REMI representation

reply for 2., following code is from this github ( transformer/workspace/main_cp.py), I thought it would generate npy files in the end of model generation.
![image](https://user-images.githubusercontent.com/48942210/152727217-87c8f201-7749-47a1-839e-672d39683451.png)

**Comment by joann8512** [comment]
To your earlier question "Models will generate .npy files, and are they the same as "corpus" in preprocessing?", if you go check the function `write_midi` as used in line# 454 (which also uses the parameter res), you can see that it is not corpus that's being written into npy.
